version: "3"
services:

  db:
    image: mysql:0.3
    container_name: mysql-wiki
    build: db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /home/newton.lee/VOLUME4DOCKER/jenkins_jobs:/var/jenkins_home/jobs
    environment:
      MYSQL_ROOT_PASSWORD: admin123
  wiki:
    image: wiki:0.3
    container_name: wiki
    build: wiki
    ports:
      - "10000:10000"

#  mysql:
#    build:
#      dockerfile: Dockerfile
#      context: mysql
#    image: ${IMAGE_NAME}:${ALPINE_VERSION}
#    container_name: ${CONTAINER_NAME}
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#    volumes:
#      - .:/app
#    ports:
#      - "${HOST_ADDRESS}:3306"
